# Generated by Django 5.2 on 2025-04-10 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recipe",
            old_name="categoru",
            new_name="category",
        ),
    ]
